### PR TITLE
Add Font Weight option

### PR DESCRIPTION
**Pull request by Khaledgarbaya**

### CODE REVIEW

**Comment by jlengstorf** [comment]
hey! so I'm not opposed to adding this, but it's actually possible now using the `titleExtraConfig` option:

```js
const socialImage = getShareImage({
  title: 'Deploy a Node.js App to DigitalOcean with SSL',
  tagline: '#devops #nodejs #ssl',
  cloudName: 'jlengstorf',
  imagePublicID: 'lwj/blog-post-card',
  font: 'futura',
  titleExtraConfig: '_bold',
  textColor: '232129',
});
```

do you think it's worth the extra setting to make it explicit?

cc @jsjoeio for input

**Comment by jsjoeio** [comment]
@Khaledgarbaya I was trying to do the same thing! Jason and I were just chatting about this on Discord.

Good question about whether it's worth it or not.

If it's possible to do this already, then maybe it would be worth it to leave as is and instead, add an example to the `README` so people know how to do it. Some thoughts on how we could do this:

- add an example column to the options table, 
- add an FAQ or examples section to the README itself

**Comment by jlengstorf** [comment]
examples would be super cool — I'd love to have the examples you both built linked from the README so people can see how this package can be used in different contexts

FAQ would also be cool, though I'm not sure if there are many Qs right now

**Comment by jsjoeio** [comment]
After I refactor ours at @echobind, I'll submit a PR to add as an example 😄

**Comment by Khaledgarbaya** [comment]
@jlengstorf Alright sounds great I will add a screenshot of my social card and an example config. I will do it in a separate PR

**Comment by jlengstorf** [comment]
thanks @Khaledgarbaya!

**Pull request closed without merging**
